version: '3.2'
services:
  app:
    image: wordpress:4.9.5
    ports:
      - "80:80"
    environment:
      RDS_USERNAME: awsignite
      RDS_DB_NAME: bootcamp
      RDS_PASSWORD: awsignitepass
      RDS_HOSTNAME: bootcamp # bootcamp-ID.us-east-1c.rds.amazonaws.com#
      RDS_PORT: 5432