Resources:

  # Este recurso crea un Grupo de Seguridad para la instancia EC2
  MyEC2SecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'  # Tipo de recurso para un grupo de seguridad de EC2
    Properties:
      GroupDescription: Security Group for EC2 instances  # Descripción del grupo de seguridad
      VpcId: <VPC-ID>  # ID de la VPC a la que se debe asociar el grupo de seguridad
      SecurityGroupIngress:
        - IpProtocol: tcp  # Protocolo que se va a permitir
          FromPort: 80  # Puerto inicial del rango de puertos que se va a permitir
          ToPort: 80  # Puerto final del rango de puertos que se va a permitir
          CidrIp: 0.0.0.0/0  # Rango de direcciones IP a las que se va a permitir el acceso

  # Este recurso crea una instancia EC2
  MyEC2Instance:
    Type: 'AWS::EC2::Instance'  # Tipo de recurso para una instancia EC2
    Properties:
      ImageId: ami-0abcdef1234567890  # ID de la imagen de la máquina de Amazon (AMI) a utilizar para la instancia
      InstanceType: t2.micro  # Tipo de instancia que se va a utilizar
      SubnetId: <SUBNET-ID>  # ID de la Subnet en la que se va a lanzar la instancia
      SecurityGroupIds:
        - !Ref MyEC2SecurityGroup  # Referencia al grupo de seguridad creado anteriormente
      # Script de usuario que se va a ejecutar en la instancia cuando se inicie
      UserData:
        Fn::Base64: |
          #!/bin/bash
          yum update -y
          yum install -y httpd
          echo "Bootcamp AWS Ingnite 2023!" > /var/www/html/index.html
          service httpd start
          chkconfig httpd on
